services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file:
      - path: ./default.env
        required: true
      - path: ./.env
        required: false
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}' ]
      interval: 5s
    ports:
      - "5432:5432"
    environment:
      PGDATA: /data/pgdata
    volumes:
        - ./pgdata:/data/pgdata
  postgres_migration:
    build:
      context: 
        ./migrations
    restart: on-failure:5
    env_file:
      - path: ./default.env
        required: true
      - path: ./.env
        required: false
    depends_on:
      postgres:
        condition: service_healthy 
  catalog_service:
    build:
      context: catalog/
    ports:
      - "5001:5001"
    restart: on-failure:5
    depends_on:
      postgres:
        condition: service_healthy
      postgres_migration:
        condition: service_completed_successfully
    env_file:
      - path: ./default.env
        required: true
      - path: ./.env
        required: false
  cart_service:
    build:
      context: cart/
    ports:
      - "5002:5002"
    restart: on-failure:5
    depends_on:
      postgres:
        condition: service_healthy
      postgres_migration:
        condition: service_completed_successfully
    env_file:
      - path: ./default.env
        required: true
      - path: ./.env
        required: false
  order_service:
    build:
      context: order/
    ports:
      - "5003:5003"
    restart: on-failure:5
    depends_on:
      postgres:
        condition: service_healthy
      postgres_migration:
        condition: service_completed_successfully
    env_file:
      - path: ./default.env
        required: true
      - path: ./.env
        required: false
  bot_service:
    build:
      context: bot/
    restart: on-failure:5
    depends_on:
      postgres:
        condition: service_healthy
      postgres_migration:
        condition: service_completed_successfully
    env_file:
      - path: ./default.env
        required: true
      - path: ./.env
        required: false
volumes:
  pgdata:
    driver: local