services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file:
      - path: ./default.env
        required: true
      - path: ./.env
        required: false
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}' ]
      interval: 5s
    ports:
      - "5432:5432"
    environment:
      PGDATA: /data/pgdata
    volumes:
        - ./pgdata:/data/pgdata
  catalog_service:
    build:
      context: catalog_service/
    ports:
      - "5001:5001"
    restart: on-failure:5
    depends_on:
      - postgres
    env_file:
      - path: ./default.env
        required: true
      - path: ./.env
        required: false
volumes:
  pgdata:
    driver: local