// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: pkg/proto/cart.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCartIdByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartIdByUserIdRequest) Reset() {
	*x = GetCartIdByUserIdRequest{}
	mi := &file_pkg_proto_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartIdByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartIdByUserIdRequest) ProtoMessage() {}

func (x *GetCartIdByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartIdByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetCartIdByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{0}
}

func (x *GetCartIdByUserIdRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCartIdByUserIdReponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        uint64                 `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartIdByUserIdReponse) Reset() {
	*x = GetCartIdByUserIdReponse{}
	mi := &file_pkg_proto_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartIdByUserIdReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartIdByUserIdReponse) ProtoMessage() {}

func (x *GetCartIdByUserIdReponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartIdByUserIdReponse.ProtoReflect.Descriptor instead.
func (*GetCartIdByUserIdReponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{1}
}

func (x *GetCartIdByUserIdReponse) GetCartId() uint64 {
	if x != nil {
		return x.CartId
	}
	return 0
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        uint64                 `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_pkg_proto_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartRequest) GetCartId() uint64 {
	if x != nil {
		return x.CartId
	}
	return 0
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_pkg_proto_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCartResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCartResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CartId        uint64                 `protobuf:"varint,2,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	ItemId        uint64                 `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      uint32                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_pkg_proto_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{4}
}

func (x *CartItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItem) GetCartId() uint64 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *CartItem) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CartItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CartItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        uint64                 `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartRequest) Reset() {
	*x = RemoveCartRequest{}
	mi := &file_pkg_proto_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartRequest) ProtoMessage() {}

func (x *RemoveCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveCartRequest) GetCartId() uint64 {
	if x != nil {
		return x.CartId
	}
	return 0
}

type RemoveCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartResponse) Reset() {
	*x = RemoveCartResponse{}
	mi := &file_pkg_proto_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartResponse) ProtoMessage() {}

func (x *RemoveCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartResponse.ProtoReflect.Descriptor instead.
func (*RemoveCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cart_proto_rawDescGZIP(), []int{6}
}

var File_pkg_proto_cart_proto protoreflect.FileDescriptor

const file_pkg_proto_cart_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/cart.proto\x12\x04cart\"3\n" +
	"\x18GetCartIdByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"3\n" +
	"\x18GetCartIdByUserIdReponse\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\x04R\x06cartId\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\x04R\x06cartId\"`\n" +
	"\x0fGetCartResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12$\n" +
	"\x05items\x18\x03 \x03(\v2\x0e.cart.CartItemR\x05items\"|\n" +
	"\bCartItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\acart_id\x18\x02 \x01(\x04R\x06cartId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\x04R\x06itemId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\rR\bquantity\",\n" +
	"\x11RemoveCartRequest\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\x04R\x06cartId\"\x14\n" +
	"\x12RemoveCartResponse2\xd4\x01\n" +
	"\x04Cart\x126\n" +
	"\aGetCart\x12\x14.cart.GetCartRequest\x1a\x15.cart.GetCartResponse\x12S\n" +
	"\x11GetCartIdByUserId\x12\x1e.cart.GetCartIdByUserIdRequest\x1a\x1e.cart.GetCartIdByUserIdReponse\x12?\n" +
	"\n" +
	"RemoveCart\x12\x17.cart.RemoveCartRequest\x1a\x18.cart.RemoveCartResponseB\bZ\x06/protob\x06proto3"

var (
	file_pkg_proto_cart_proto_rawDescOnce sync.Once
	file_pkg_proto_cart_proto_rawDescData []byte
)

func file_pkg_proto_cart_proto_rawDescGZIP() []byte {
	file_pkg_proto_cart_proto_rawDescOnce.Do(func() {
		file_pkg_proto_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_cart_proto_rawDesc), len(file_pkg_proto_cart_proto_rawDesc)))
	})
	return file_pkg_proto_cart_proto_rawDescData
}

var file_pkg_proto_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_cart_proto_goTypes = []any{
	(*GetCartIdByUserIdRequest)(nil), // 0: cart.GetCartIdByUserIdRequest
	(*GetCartIdByUserIdReponse)(nil), // 1: cart.GetCartIdByUserIdReponse
	(*GetCartRequest)(nil),           // 2: cart.GetCartRequest
	(*GetCartResponse)(nil),          // 3: cart.GetCartResponse
	(*CartItem)(nil),                 // 4: cart.CartItem
	(*RemoveCartRequest)(nil),        // 5: cart.RemoveCartRequest
	(*RemoveCartResponse)(nil),       // 6: cart.RemoveCartResponse
}
var file_pkg_proto_cart_proto_depIdxs = []int32{
	4, // 0: cart.GetCartResponse.items:type_name -> cart.CartItem
	2, // 1: cart.Cart.GetCart:input_type -> cart.GetCartRequest
	0, // 2: cart.Cart.GetCartIdByUserId:input_type -> cart.GetCartIdByUserIdRequest
	5, // 3: cart.Cart.RemoveCart:input_type -> cart.RemoveCartRequest
	3, // 4: cart.Cart.GetCart:output_type -> cart.GetCartResponse
	1, // 5: cart.Cart.GetCartIdByUserId:output_type -> cart.GetCartIdByUserIdReponse
	6, // 6: cart.Cart.RemoveCart:output_type -> cart.RemoveCartResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_cart_proto_init() }
func file_pkg_proto_cart_proto_init() {
	if File_pkg_proto_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_cart_proto_rawDesc), len(file_pkg_proto_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_cart_proto_goTypes,
		DependencyIndexes: file_pkg_proto_cart_proto_depIdxs,
		MessageInfos:      file_pkg_proto_cart_proto_msgTypes,
	}.Build()
	File_pkg_proto_cart_proto = out.File
	file_pkg_proto_cart_proto_goTypes = nil
	file_pkg_proto_cart_proto_depIdxs = nil
}
