// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: pkg/proto/order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderByCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        uint64                 `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderByCartRequest) Reset() {
	*x = CreateOrderByCartRequest{}
	mi := &file_pkg_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderByCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderByCartRequest) ProtoMessage() {}

func (x *CreateOrderByCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderByCartRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderByCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderByCartRequest) GetCartId() uint64 {
	if x != nil {
		return x.CartId
	}
	return 0
}

type CreateOrderByCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderByCartResponse) Reset() {
	*x = CreateOrderByCartResponse{}
	mi := &file_pkg_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderByCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderByCartResponse) ProtoMessage() {}

func (x *CreateOrderByCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderByCartResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderByCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_order_proto_rawDescGZIP(), []int{1}
}

var File_pkg_proto_order_proto protoreflect.FileDescriptor

const file_pkg_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/order.proto\x12\x05order\"3\n" +
	"\x18CreateOrderByCartRequest\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\x04R\x06cartId\"\x1b\n" +
	"\x19CreateOrderByCartResponse2_\n" +
	"\x05Order\x12V\n" +
	"\x11CreateOrderByCart\x12\x1f.order.CreateOrderByCartRequest\x1a .order.CreateOrderByCartResponseB\bZ\x06/protob\x06proto3"

var (
	file_pkg_proto_order_proto_rawDescOnce sync.Once
	file_pkg_proto_order_proto_rawDescData []byte
)

func file_pkg_proto_order_proto_rawDescGZIP() []byte {
	file_pkg_proto_order_proto_rawDescOnce.Do(func() {
		file_pkg_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_order_proto_rawDesc), len(file_pkg_proto_order_proto_rawDesc)))
	})
	return file_pkg_proto_order_proto_rawDescData
}

var file_pkg_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_order_proto_goTypes = []any{
	(*CreateOrderByCartRequest)(nil),  // 0: order.CreateOrderByCartRequest
	(*CreateOrderByCartResponse)(nil), // 1: order.CreateOrderByCartResponse
}
var file_pkg_proto_order_proto_depIdxs = []int32{
	0, // 0: order.Order.CreateOrderByCart:input_type -> order.CreateOrderByCartRequest
	1, // 1: order.Order.CreateOrderByCart:output_type -> order.CreateOrderByCartResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_order_proto_init() }
func file_pkg_proto_order_proto_init() {
	if File_pkg_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_order_proto_rawDesc), len(file_pkg_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_order_proto_goTypes,
		DependencyIndexes: file_pkg_proto_order_proto_depIdxs,
		MessageInfos:      file_pkg_proto_order_proto_msgTypes,
	}.Build()
	File_pkg_proto_order_proto = out.File
	file_pkg_proto_order_proto_goTypes = nil
	file_pkg_proto_order_proto_depIdxs = nil
}
