// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: pkg/proto/catalog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductsByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByTypeRequest) Reset() {
	*x = GetProductsByTypeRequest{}
	mi := &file_pkg_proto_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByTypeRequest) ProtoMessage() {}

func (x *GetProductsByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByTypeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductsByTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetProductsByTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByTypeResponse) Reset() {
	*x = GetProductsByTypeResponse{}
	mi := &file_pkg_proto_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByTypeResponse) ProtoMessage() {}

func (x *GetProductsByTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByTypeResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByTypeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsByTypeResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_pkg_proto_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_pkg_proto_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Topping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topping) Reset() {
	*x = Topping{}
	mi := &file_pkg_proto_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topping) ProtoMessage() {}

func (x *Topping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topping.ProtoReflect.Descriptor instead.
func (*Topping) Descriptor() ([]byte, []int) {
	return file_pkg_proto_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Topping) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topping) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Topping) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topping) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_pkg_proto_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_pkg_proto_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductToppingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Toppings      []*Topping             `protobuf:"bytes,1,rep,name=toppings,proto3" json:"toppings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductToppingsResponse) Reset() {
	*x = GetProductToppingsResponse{}
	mi := &file_pkg_proto_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductToppingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductToppingsResponse) ProtoMessage() {}

func (x *GetProductToppingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductToppingsResponse.ProtoReflect.Descriptor instead.
func (*GetProductToppingsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductToppingsResponse) GetToppings() []*Topping {
	if x != nil {
		return x.Toppings
	}
	return nil
}

type GetToppingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToppingRequest) Reset() {
	*x = GetToppingRequest{}
	mi := &file_pkg_proto_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToppingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToppingRequest) ProtoMessage() {}

func (x *GetToppingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToppingRequest.ProtoReflect.Descriptor instead.
func (*GetToppingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetToppingRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetToppingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topping       *Topping               `protobuf:"bytes,1,opt,name=topping,proto3" json:"topping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToppingResponse) Reset() {
	*x = GetToppingResponse{}
	mi := &file_pkg_proto_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToppingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToppingResponse) ProtoMessage() {}

func (x *GetToppingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToppingResponse.ProtoReflect.Descriptor instead.
func (*GetToppingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *GetToppingResponse) GetTopping() *Topping {
	if x != nil {
		return x.Topping
	}
	return nil
}

var File_pkg_proto_catalog_proto protoreflect.FileDescriptor

const file_pkg_proto_catalog_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/catalog.proto\x12\acatalog\".\n" +
	"\x18GetProductsByTypeRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"I\n" +
	"\x19GetProductsByTypeResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.catalog.ProductR\bproducts\"y\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"b\n" +
	"\aTopping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"@\n" +
	"\x12GetProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.catalog.ProductR\aproduct\"J\n" +
	"\x1aGetProductToppingsResponse\x12,\n" +
	"\btoppings\x18\x01 \x03(\v2\x10.catalog.ToppingR\btoppings\"#\n" +
	"\x11GetToppingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"@\n" +
	"\x12GetToppingResponse\x12*\n" +
	"\atopping\x18\x01 \x01(\v2\x10.catalog.ToppingR\atopping2\xca\x02\n" +
	"\aCatalog\x12E\n" +
	"\n" +
	"GetProduct\x12\x1a.catalog.GetProductRequest\x1a\x1b.catalog.GetProductResponse\x12U\n" +
	"\x12GetProductToppings\x12\x1a.catalog.GetProductRequest\x1a#.catalog.GetProductToppingsResponse\x12E\n" +
	"\n" +
	"GetTopping\x12\x1a.catalog.GetToppingRequest\x1a\x1b.catalog.GetToppingResponse\x12Z\n" +
	"\x11GetProductsByType\x12!.catalog.GetProductsByTypeRequest\x1a\".catalog.GetProductsByTypeResponseB\bZ\x06/protob\x06proto3"

var (
	file_pkg_proto_catalog_proto_rawDescOnce sync.Once
	file_pkg_proto_catalog_proto_rawDescData []byte
)

func file_pkg_proto_catalog_proto_rawDescGZIP() []byte {
	file_pkg_proto_catalog_proto_rawDescOnce.Do(func() {
		file_pkg_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_catalog_proto_rawDesc), len(file_pkg_proto_catalog_proto_rawDesc)))
	})
	return file_pkg_proto_catalog_proto_rawDescData
}

var file_pkg_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_catalog_proto_goTypes = []any{
	(*GetProductsByTypeRequest)(nil),   // 0: catalog.GetProductsByTypeRequest
	(*GetProductsByTypeResponse)(nil),  // 1: catalog.GetProductsByTypeResponse
	(*Product)(nil),                    // 2: catalog.Product
	(*Topping)(nil),                    // 3: catalog.Topping
	(*GetProductRequest)(nil),          // 4: catalog.GetProductRequest
	(*GetProductResponse)(nil),         // 5: catalog.GetProductResponse
	(*GetProductToppingsResponse)(nil), // 6: catalog.GetProductToppingsResponse
	(*GetToppingRequest)(nil),          // 7: catalog.GetToppingRequest
	(*GetToppingResponse)(nil),         // 8: catalog.GetToppingResponse
}
var file_pkg_proto_catalog_proto_depIdxs = []int32{
	2, // 0: catalog.GetProductsByTypeResponse.products:type_name -> catalog.Product
	2, // 1: catalog.GetProductResponse.product:type_name -> catalog.Product
	3, // 2: catalog.GetProductToppingsResponse.toppings:type_name -> catalog.Topping
	3, // 3: catalog.GetToppingResponse.topping:type_name -> catalog.Topping
	4, // 4: catalog.Catalog.GetProduct:input_type -> catalog.GetProductRequest
	4, // 5: catalog.Catalog.GetProductToppings:input_type -> catalog.GetProductRequest
	7, // 6: catalog.Catalog.GetTopping:input_type -> catalog.GetToppingRequest
	0, // 7: catalog.Catalog.GetProductsByType:input_type -> catalog.GetProductsByTypeRequest
	5, // 8: catalog.Catalog.GetProduct:output_type -> catalog.GetProductResponse
	6, // 9: catalog.Catalog.GetProductToppings:output_type -> catalog.GetProductToppingsResponse
	8, // 10: catalog.Catalog.GetTopping:output_type -> catalog.GetToppingResponse
	1, // 11: catalog.Catalog.GetProductsByType:output_type -> catalog.GetProductsByTypeResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_catalog_proto_init() }
func file_pkg_proto_catalog_proto_init() {
	if File_pkg_proto_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_catalog_proto_rawDesc), len(file_pkg_proto_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_catalog_proto_goTypes,
		DependencyIndexes: file_pkg_proto_catalog_proto_depIdxs,
		MessageInfos:      file_pkg_proto_catalog_proto_msgTypes,
	}.Build()
	File_pkg_proto_catalog_proto = out.File
	file_pkg_proto_catalog_proto_goTypes = nil
	file_pkg_proto_catalog_proto_depIdxs = nil
}
